source 'https://rubygems.org'

gem 'better_errors'
gem 'binding_of_caller'
gem 'formtastic'
gem 'haml-rails'
gem 'rails'
gem 'sqlite3'
gem 'virtus'

gem 'form_objects', path: '/home/martin/code/gems/form_objects'
