source 'https://rubygems.org'

gem 'better_errors'
gem 'binding_of_caller'
gem 'formtastic', '< 3.0'
gem 'formtastic-bootstrap'
gem 'haml-rails'
gem 'rails'
gem 'sqlite3'
gem 'virtus'

group :assets do
  gem 'coffee-rails'
end

gem 'form_this', path: '../'
